
#Common settings
[common]
	#The maximum number of blocks that can be excavated at once
	#Range: > 1
	Limit = 128
	#How many blocks per tick can be excavated
	#Range: > 1
	Speed = 64
	#How far from the origin an excavation can travel
	#Range: > 1
	Range = 16
	#Amount of exhaustion per block excavated
	#Range: 0.0 ~ 1.7976931348623157E308
	Ehxaustion = 0.1
	#Experience cost per block excavated
	#Range: > 0
	Experience = 0
	#Allow excavation with an open hand
	"Open Hand" = true
	#Inverts the tool blacklist to function as a whitelist
	"Invert Tool Blacklist" = false
	#Inverts the block blacklist to function as a whitelist
	"Invert Block Blacklist" = true
	#Ignores whether or not the held tool is valid
	"Ignore Tool" = false
	#Use alternate check for tool validity (e.g. swords on webs)
	"Alt Tools" = false
	#Limit excavation to standard tool types (Picks, Shoves, Axes & Shears)
	"Only Standard Types" = false
	#Temporarily reduces excavation speed if TPS begins to slow down
	"TPS Guard" = true
	#Skips spawning drops in world adding them directly to your inventory
	"Auto Pickup" = false
	#Allow players to use shape mining
	"Allow Shapes" = true
	#How many excavations should be kept in undo history (may lead to exploits or instability)
	#Range: > 0
	"Max Undos" = 3
	#Allows excavation undo function to work through liquids and other replaceable blocks
	"Undo Replaceables " = true
	#The default game stage required to unlock excavations (requires gamestages to be installed)
	"Game Stage" = ""
	#Tools blacklisted from excavating
	"Tool Blacklist" = []
	#Blocks blacklisted from being excavated
	"Block Blacklist" = ["minecraft:coal_ore", "minecraft:deepslate_coal_ore", "minecraft:iron_ore", "minecraft:deepslate_iron_ore", "minecraft:copper_ore", "minecraft:deepslate_copper_ore", "minecraft:gold_ore", "minecraft:deepslate_gold_ore", "minecraft:redstone_ore", "minecraft:deepslate_redstone_ore", "minecraft:emerald_ore", "minecraft:deepslate_emerald_ore", "minecraft:lapis_ore", "minecraft:deepslate_lapis_ore", "minecraft:diamond_ore", "minecraft:deepslate_diamond_ore", "minecraft:nether_gold_ore", "minecraft:nether_quartz_ore", "ad_astra:moon_cheese_ore", "ad_astra:moon_desh_ore", "ad_astra:deepslate_desh_ore", "ad_astra:moon_iron_ore", "ad_astra:moon_ice_shard_ore", "ad_astra:deepslate_ice_shard_ore", "ad_astra:mars_iron_ore", "ad_astra:mars_diamond_ore", "ad_astra:mars_ostrum_ore", "ad_astra:deepslate_ostrum_ore", "ad_astra:mars_ice_shard_ore", "ad_astra:venus_coal_ore", "ad_astra:venus_gold_ore", "ad_astra:venus_diamond_ore", "ad_astra:venus_calorite_ore", "ad_astra:deepslate_calorite_ore", "ad_astra:mercury_iron_ore", "ad_astra:glacio_ice_shard_ore", "ad_astra:glacio_coal_ore", "ad_astra:glacio_copper_ore", "ad_astra:glacio_iron_ore", "ad_astra:glacio_lapis_ore", "alexscaves:galena_iron_ore", "alexscaves:radrock_uranium_ore", "alexscaves:guanostone_redstone_ore", "alexscaves:coprolith_coal_ore", "create:zinc_ore", "create:deepslate_zinc_ore", "create_new_age:thorium_ore", "enlightened_end:malachite_ore", "enlightened_end:irradium_ore", "enlightened_end:bismuth_ore", "bigreactors:yellorite_ore", "bigreactors:anglesite_ore", "bigreactors:benitoite_ore", "iceandfire:silver_ore", "iceandfire:deepslate_silver_ore", "iceandfire:sapphire_ore", "immersiveengineering:ore_aluminum", "immersiveengineering:deepslate_ore_aluminum", "immersiveengineering:ore_lead", "immersiveengineering:deepslate_ore_lead", "immersiveengineering:ore_silver", "immersiveengineering:deepslate_ore_silver", "immersiveengineering:ore_nickel", "immersiveengineering:deepslate_ore_nickel", "immersiveengineering:ore_uranium", "immersiveengineering:deepslate_ore_uranium", "mekanism:tin_ore", "mekanism:deepslate_tin_ore", "mekanism:osmium_ore", "mekanism:deepslate_osmium_ore", "mekanism:uranium_ore", "mekanism:deepslate_uranium_ore", "mekanism:fluorite_ore", "mekanism:deepslate_fluorite_ore", "mekanism:lead_ore", "mekanism:deepslate_lead_ore", "mysticalagradditions:nether_prosperity_ore", "mysticalagradditions:nether_inferium_ore", "mysticalagradditions:end_prosperity_ore", "mysticalagradditions:end_inferium_ore", "mysticalagriculture:prosperity_ore", "mysticalagriculture:deepslate_prosperity_ore", "mysticalagriculture:inferium_ore", "mysticalagriculture:deepslate_inferium_ore", "mysticalagriculture:soulium_ore", "nuclearcraft:magnesium_deepslate_ore", "nuclearcraft:thorium_deepslate_ore", "nuclearcraft:uranium_deepslate_ore", "nuclearcraft:magnesium_ore", "nuclearcraft:boron_deepslate_ore", "nuclearcraft:cobalt_ore", "nuclearcraft:platinum_deepslate_ore", "nuclearcraft:silver_deepslate_ore", "nuclearcraft:lead_ore", "nuclearcraft:lithium_ore", "nuclearcraft:thorium_ore", "nuclearcraft:tin_ore", "nuclearcraft:cobalt_deepslate_ore", "nuclearcraft:silver_ore", "nuclearcraft:uranium_ore", "nuclearcraft:zinc_ore", "nuclearcraft:boron_ore", "nuclearcraft:lithium_deepslate_ore", "rftoolsbase:dimensionalshard_overworld", "rftoolsbase:dimensionalshard_nether", "rftoolsbase:dimensionalshard_end", "aether:ambrosium_ore", "aether:zanite_ore", "aether:gravitite_ore", "thermal:apatite_ore", "thermal:deepslate_apatite_ore", "thermal:cinnabar_ore", "thermal:deepslate_cinnabar_ore", "thermal:niter_ore", "thermal:deepslate_niter_ore", "thermal:sulfur_ore", "thermal:deepslate_sulfur_ore", "thermal:tin_ore", "thermal:deepslate_tin_ore", "thermal:lead_ore", "thermal:deepslate_lead_ore", "thermal:silver_ore", "thermal:deepslate_silver_ore", "thermal:nickel_ore", "thermal:deepslate_nickel_ore", "thermal:ruby_ore", "thermal:deepslate_ruby_ore", "thermal:sapphire_ore", "thermal:deepslate_sapphire_ore", "minecraft:oak_log", "minecraft:spruce_log", "minecraft:birch_log", "minecraft:jungle_log", "minecraft:acacia_log", "minecraft:dark_oak_log"]

